# Generated by Django 6.1.1 on 2026-09-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuruProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Shiva Yogi Guru', max_length=100)),
                ('title', models.CharField(default='Chief Astrologer & Spiritual Guide', max_length=200)),
                ('bio', models.TextField(default='Welcome to Shiva Yogi Jotish Kendra. We provide authentic Vedic astrology, horoscope analysis, and spiritual healing solutions.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='guru/')),
            ],
        ),
    ]
